### ISSUE TITLE
Check for CloudFlare API Keys

### ISSUE THREAD

**Issue by shodges-vermeer** [vermeer-corp/sec-ci-actions#12]
Use case: We're looking into using GitHub Actions to manage DNS records in CloudFlare. 

Ideally I'd like to have gitleaks check for those types of keys. It doesn't look like the repo you forked this from has support for this, and my very cursury glance at Google didn't show that CF uses any recognizable pattern, but maybe you'll find something.

Example Key: EwOrUSJo8e4YCLMXDqiqRWJNVCJwaxvgGR03QbU4

(Key was generated with read only privileges and was immediately revoked)

**Comment by lawndoc** [comment]
I think that this would be already detected with the "generic" secret rule which looks at variable name + secret entropy

**Comment by lawndoc** [comment]
Also, next time please don't paste a valid secret even if it was revoked (it's really asking for mistakes to be made). You can modify multiple characters to make it invalid or describe it in terms of regex instead.

**Comment by shodges-vermeer** [comment]
Fantastic, Thanks CJ!
